### ISSUE TITLE
Drop down menu under account icon is blurry

### ISSUE THREAD

**Issue by littleboy0k** [Novusphere/eos-forum#23]
The font in

![image](https://user-images.githubusercontent.com/32856591/51007774-ca461380-1583-11e9-8c4a-aec1039271c0.png)

is hitting on my eyes. I would like to suggest changing the style of that element.

**Comment by Novusphere** [comment]
@kodoburu could you take a look at this? I'm not sure if it's been changed with any recent changes.

**Comment by littleboy0k** [comment]
@Novusphere This issue doesn't exist in discussions.app. Closing.
