### ISSUE TITLE
Subscription is not working. 

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/eos-forum#69]
After subscribing to subs, it does not show up from the list of drop-downs/side-subs.

**Comment by Novusphere** [comment]
I'm not able to reproduce this issue, both the side subs, and the drop down subs seem to update accordingly when subscribing/unsubscribing to subs. Note that subs are ordered alphabetically.

**Comment by bluabaleno** [comment]
try subscribing to e/meatlpackagingtoken

**Comment by Novusphere** [comment]
@bluabaleno https://i.imgur.com/ejwBuL2.png works fine?

**Comment by Novusphere** [comment]
Fixed in conjunction with #68
